FOOTYSTATS_TEAM_MAP = {
    "Roma": "AS Roma",
    "AFC Bournemouth": "Bournemouth",
    "Almería": "Almeria",
    "América Mineiro": "America Mineiro",
    "Angers SCO": "Angers",
    "Athletic Club Bilbao": "Ath Bilbao",
    "Atlético GO": "Atletico GO",
    "Atlético Madrid": "Atl. Madrid",
    "Atlético PR": "Athletico-PR",
    "Bayern München": "Bayern Munich",
    "Boavista FC": "Boavista",
    "Borussia Dortmund": "Dortmund",
    "Borussia M'gladbach": "B. Monchengladbach",
    "Botafogo": "Botafogo RJ",
    "Brighton & Hove Albion": "Brighton",
    "CA Osasuna": "Osasuna",
    "CD Nacional": "Nacional",
    "CD Tondela": "Tondela",
    "Ceará": "Ceara",
    "Celta de Vigo": "Celta Vigo",
    "Chapecoense": "Chapecoense-SC",
    "Criciúma": "Criciuma",
    "Cuiabá": "Cuiaba",
    "Cádiz": "Cadiz CF",
    "Darmstadt 98": "Darmstadt",
    "Deportivo Alavés": "Alaves",
    "Elche CF": "Elche",
    "Estrela Amadora": "Estrela",
    "FC Arouca": "Arouca",
    "FC Barcelona": "Barcelona",
    "FC Vizela": "Vizela",
    "Famalicão": "Famalicao",
    "Flamengo": "Flamengo RJ",
    "GD Chaves": "Chaves",
    "GD Estoril Praia": "Estoril",
    "Getafe CF": "Getafe",
    "Girona FC": "Girona",
    "Grêmio": "Gremio",
    "Hellas Verona": "Verona",
    "Inter Milan": "Inter",
    "Ipswich Town": "Ipswich",
    "Köln": "FC Koln",
    "Leeds United": "Leeds",
    "Leganés": "Leganes",
    "Leicester City": "Leicester",
    "Levante UD": "Levante",
    "Luton Town": "Luton",
    "Mainz 05": "Mainz",
    "Manchester United": "Manchester Utd",
    "Moreirense FC": "Moreirense",
    "Newcastle United": "Newcastle",
    "Nottingham Forest": "Nottingham",
    "Olympique Lyonnais": "Lyon",
    "Olympique Marseille": "Marseille",
    "Paris": "Paris FC",
    "Porto": "FC Porto",
    "RCD Espanyol": "Espanyol",
    "RCD Mallorca": "Mallorca",
    "Real Betis": "Betis",
    "Real Oviedo": "R. Oviedo",
    "Real Valladolid": "Valladolid",
    "Rio Ave FC": "Rio Ave",
    "Saint-Étienne": "St Etienne",
    "Sevilla FC": "Sevilla",
    "Sheffield United": "Sheffield Utd",
    "Sporting Braga": "Braga",
    "Sporting CP": "Sporting CP",
    "São Paulo": "Sao Paulo",
    "Tottenham Hotspur": "Tottenham",
    "UD Las Palmas": "Las Palmas",
    "Valencia CF": "Valencia",
    "Vasco da Gama": "Vasco",
    "Vitória": "Vitoria",
    "Vitória Guimarães": "Vitoria Guimaraes",
    "West Ham United": "West Ham",
    "Wolverhampton Wanderers": "Wolves",
}


def map_team_name(name):
    if name is None:
        return ""
    value = str(name).strip()
    return FOOTYSTATS_TEAM_MAP.get(value, value)


def is_known_team_name(name):
    if name is None:
        return False
    value = str(name).strip()
    return value in FOOTYSTATS_TEAM_MAP or value in FOOTYSTATS_TEAM_MAP.values()
